#!/bin/bash
echo "Total number of parameters are = $#"
echo "Script name = $0"
echo "First Parameter = $1"
echo "Second Parameter = $2"
echo "Third Parameter = $3"
echo "Fourth Parameter = $4"
echo "Fifth Parameter = $5"
echo "All parameters by "'$*'" = $*"
echo "All elements by "'$@'" = $@"
printf "All elements by \"\$*\" = %s\n" "$*"
printf "All elements by \"\$@\" = %s\n" "$@"